behaviors:
  DwarfBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 2048
      learning_rate: 3e-4
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 32
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.995
        strength: 0.005
        network_settings:
          hidden_units: 32
        learning_rate: 3e-4
    max_steps: 4000000
    time_horizon: 5
    summary_freq: 10000